/*
  Development sample data only. Do not use in production.
  Active public pages and dashboards now load Umusare data from the backend API.
  Private driver document images must never be displayed publicly; only verification status should be shown.
*/
window.UmusareSampleData = {
  drivers: [
    {
      driverId: "drv-001",
      slug: "amina-mutesi",
      fullName: "Amina Mutesi",
      firstName: "Amina",
      initials: "AM",
      gender: "Female",
      age: 34,
      phone: "+250 788 000 111",
      email: "amina.mutesi@example.com",
      city: "Kigali",
      location: "Kigali City",
      profilePhoto: "",
      rating: 4.9,
      reviewCount: 128,
      completedTrips: 186,
      experienceYears: 7,
      languages: ["Kinyarwanda", "English", "French"],
      vehicleTypes: ["Automatic", "Manual", "SUV", "Luxury car"],
      availability: "Available Now",
      driverBadge: "Top Driver",
      subscriptionPlan: "Pro",
      subscriptionStatus: "Active",
      monthlyFee: "5,000 RWF",
      renewalDate: "July 8, 2026",
      bookingsUsedThisMonth: "Unlimited",
      profileVisibility: "Visible",
      verification: { idVerified: true, licenseVerified: true, educationVerified: true, photoVerified: true, criminalRecordVerified: true },
      criminalRecordCheck: { submitted: true, verified: true, status: "Verified" },
      shortBio: "Calm, professional designated driver with experience in city transfers, airport trips, evening pickups, and premium vehicles."
    },
    {
      driverId: "drv-002",
      slug: "jean-kamanzi",
      fullName: "Jean Kamanzi",
      firstName: "Jean",
      initials: "JK",
      gender: "Male",
      age: 41,
      phone: "+250 788 000 112",
      email: "jean.kamanzi@example.com",
      city: "Musanze",
      location: "Musanze",
      profilePhoto: "",
      rating: 4.8,
      reviewCount: 72,
      completedTrips: 119,
      experienceYears: 5,
      languages: ["Kinyarwanda", "English", "Swahili"],
      vehicleTypes: ["Manual", "Pickup", "SUV"],
      availability: "Available Later",
      driverBadge: "Pro Driver",
      subscriptionPlan: "Pro",
      subscriptionStatus: "Active",
      monthlyFee: "5,000 RWF",
      renewalDate: "July 12, 2026",
      bookingsUsedThisMonth: "Unlimited",
      profileVisibility: "Visible",
      verification: { idVerified: true, licenseVerified: true, educationVerified: true, photoVerified: true, criminalRecordVerified: true },
      criminalRecordCheck: { submitted: true, verified: true, status: "Verified" },
      shortBio: "Experienced long-distance and mountain-road driver with careful handling of manual cars and pickups."
    },
    {
      driverId: "drv-003",
      slug: "chantal-niyonsaba",
      fullName: "Chantal Niyonsaba",
      firstName: "Chantal",
      initials: "CN",
      gender: "Female",
      age: 38,
      phone: "+250 788 000 113",
      email: "chantal.niyonsaba@example.com",
      city: "Huye",
      location: "Huye",
      profilePhoto: "",
      rating: 4.7,
      reviewCount: 54,
      completedTrips: 94,
      experienceYears: 9,
      languages: ["Kinyarwanda", "French"],
      vehicleTypes: ["Automatic", "Manual", "Luxury car"],
      availability: "Available Now",
      driverBadge: "Verified Driver",
      subscriptionPlan: "Basic",
      subscriptionStatus: "Pending",
      monthlyFee: "2,500 RWF",
      renewalDate: "June 14, 2026",
      bookingsUsedThisMonth: "4 of 10",
      profileVisibility: "Hidden",
      verification: { idVerified: true, licenseVerified: true, educationVerified: true, photoVerified: true, criminalRecordVerified: false },
      criminalRecordCheck: { submitted: true, verified: false, status: "Needs Review" },
      shortBio: "Patient city and intercity driver with a strong record on planned trips."
    },
    {
      driverId: "drv-004",
      slug: "eric-paul",
      fullName: "Eric Paul",
      firstName: "Eric",
      initials: "EP",
      gender: "Male",
      age: 45,
      phone: "+250 788 000 114",
      email: "eric.paul@example.com",
      city: "Gasabo",
      location: "Gasabo",
      profilePhoto: "",
      rating: 3.2,
      reviewCount: 31,
      completedTrips: 63,
      experienceYears: 10,
      languages: ["Kinyarwanda", "English"],
      vehicleTypes: ["Automatic", "SUV", "Pickup"],
      availability: "Offline",
      driverBadge: "Pro Driver",
      subscriptionPlan: "Basic",
      subscriptionStatus: "Expired",
      monthlyFee: "2,500 RWF",
      renewalDate: "June 1, 2026",
      bookingsUsedThisMonth: "10 of 10",
      profileVisibility: "Hidden",
      verification: { idVerified: true, licenseVerified: true, educationVerified: false, photoVerified: true, criminalRecordVerified: false },
      criminalRecordCheck: { submitted: false, verified: false, status: "Missing" },
      shortBio: "Experienced SUV and pickup driver currently hidden because subscription is expired."
    },
    {
      driverId: "drv-005",
      slug: "claudine-uwera",
      fullName: "Claudine Uwera",
      firstName: "Claudine",
      initials: "CU",
      gender: "Female",
      age: 36,
      phone: "+250 788 000 115",
      email: "claudine.uwera@example.com",
      city: "Kicukiro",
      location: "Kicukiro",
      profilePhoto: "",
      rating: 5,
      reviewCount: 88,
      completedTrips: 142,
      experienceYears: 11,
      languages: ["Kinyarwanda", "English", "French"],
      vehicleTypes: ["Automatic", "SUV", "Luxury car"],
      availability: "Available Now",
      driverBadge: "Top Driver",
      subscriptionPlan: "Pro",
      subscriptionStatus: "Active",
      monthlyFee: "5,000 RWF",
      renewalDate: "July 18, 2026",
      bookingsUsedThisMonth: "Unlimited",
      profileVisibility: "Visible",
      verification: { idVerified: true, licenseVerified: true, educationVerified: true, photoVerified: true, criminalRecordVerified: true },
      criminalRecordCheck: { submitted: true, verified: true, status: "Verified" },
      shortBio: "Highly rated driver for events, airport transfers, and premium vehicles."
    },
    {
      driverId: "drv-006",
      slug: "samuel-nkurunziza",
      fullName: "Samuel Nkurunziza",
      firstName: "Samuel",
      initials: "SN",
      gender: "Male",
      age: 29,
      phone: "+250 788 000 116",
      email: "samuel.nkurunziza@example.com",
      city: "Rubavu",
      location: "Rubavu",
      profilePhoto: "",
      rating: 4.4,
      reviewCount: 19,
      completedTrips: 36,
      experienceYears: 3,
      languages: ["Kinyarwanda", "Swahili"],
      vehicleTypes: ["Manual", "Pickup"],
      availability: "Available Later",
      driverBadge: "Verified Driver",
      subscriptionPlan: "Basic",
      subscriptionStatus: "Active",
      monthlyFee: "2,500 RWF",
      renewalDate: "July 3, 2026",
      bookingsUsedThisMonth: "3 of 10",
      profileVisibility: "Visible",
      verification: { idVerified: true, licenseVerified: true, educationVerified: true, photoVerified: true, criminalRecordVerified: true },
      criminalRecordCheck: { submitted: true, verified: true, status: "Verified" },
      shortBio: "Reliable driver for manual vehicles, pickups, and lakeside trips."
    },
    {
      driverId: "drv-007",
      slug: "nadia-ishimwe",
      fullName: "Nadia Ishimwe",
      firstName: "Nadia",
      initials: "NI",
      gender: "Female",
      age: 32,
      phone: "+250 788 000 117",
      email: "nadia.ishimwe@example.com",
      city: "Nyarugenge",
      location: "Nyarugenge",
      profilePhoto: "",
      rating: 4.6,
      reviewCount: 44,
      completedTrips: 77,
      experienceYears: 6,
      languages: ["Kinyarwanda", "English"],
      vehicleTypes: ["Automatic", "SUV"],
      availability: "Available Now",
      driverBadge: "Pro Driver",
      subscriptionPlan: "Pro",
      subscriptionStatus: "Active",
      monthlyFee: "5,000 RWF",
      renewalDate: "July 20, 2026",
      bookingsUsedThisMonth: "Unlimited",
      profileVisibility: "Visible",
      verification: { idVerified: true, licenseVerified: true, educationVerified: true, photoVerified: true, criminalRecordVerified: true },
      criminalRecordCheck: { submitted: true, verified: true, status: "Verified" },
      shortBio: "Professional night-out and event driver with clear communication."
    },
    {
      driverId: "drv-008",
      slug: "patrick-habimana",
      fullName: "Patrick Habimana",
      firstName: "Patrick",
      initials: "PH",
      gender: "Male",
      age: 47,
      phone: "+250 788 000 118",
      email: "patrick.habimana@example.com",
      city: "Kigali",
      location: "Kimihurura",
      profilePhoto: "",
      rating: 4.3,
      reviewCount: 27,
      completedTrips: 58,
      experienceYears: 12,
      languages: ["Kinyarwanda", "English", "French"],
      vehicleTypes: ["Automatic", "Manual", "Luxury car"],
      availability: "Offline",
      driverBadge: "Verified Driver",
      subscriptionPlan: "Basic",
      subscriptionStatus: "Expired",
      monthlyFee: "2,500 RWF",
      renewalDate: "May 28, 2026",
      bookingsUsedThisMonth: "8 of 10",
      profileVisibility: "Hidden",
      verification: { idVerified: true, licenseVerified: false, educationVerified: true, photoVerified: true, criminalRecordVerified: false },
      criminalRecordCheck: { submitted: true, verified: false, status: "Rejected" },
      shortBio: "Senior driver hidden from public listing until subscription and licence status are updated."
    }
  ],
  clients: [
    { clientId: "cli-001", fullName: "Mika Uwase", firstName: "Mika", phone: "+250 788 555 010", email: "mika.uwase@example.com", city: "Kigali", emergencyContactName: "Eric Uwase", emergencyContactPhone: "+250 788 555 011" },
    { clientId: "cli-002", fullName: "Grace Mukamana", firstName: "Grace", phone: "+250 788 555 020", email: "grace.m@example.com", city: "Nyarugenge", emergencyContactName: "Alice Mukamana", emergencyContactPhone: "+250 788 555 021" },
    { clientId: "cli-003", fullName: "Patrick Ndayisenga", firstName: "Patrick", phone: "+250 788 555 030", email: "patrick.n@example.com", city: "Gasabo", emergencyContactName: "Diane Ndayisenga", emergencyContactPhone: "+250 788 555 031" },
    { clientId: "cli-004", fullName: "Nadia Umutesi", firstName: "Nadia", phone: "+250 788 555 040", email: "nadia.u@example.com", city: "Huye", emergencyContactName: "Claude Umutesi", emergencyContactPhone: "+250 788 555 041" },
    { clientId: "cli-005", fullName: "Daniel Bizimana", firstName: "Daniel", phone: "+250 788 555 050", email: "daniel.b@example.com", city: "Musanze", emergencyContactName: "Sarah Bizimana", emergencyContactPhone: "+250 788 555 051" }
  ],
  bookings: [
    { bookingId: "UM-2201", bookingType: "Quick Book", clientId: "cli-001", clientName: "Mika Uwase", driverId: "drv-001", driverName: "Amina Mutesi", pickupLocation: "Kigali Heights", destination: "Kacyiru", dateTime: "June 11, 2026, 9:30 PM", neededTime: "ASAP", carType: "Automatic SUV", notes: "Meet at the main lobby entrance.", status: "Accepted", lastUpdated: "June 11, 2026, 9:34 PM" },
    { bookingId: "UM-2164", bookingType: "Quick Book", clientId: "cli-002", clientName: "Grace Mukamana", driverId: "drv-005", driverName: "Claudine Uwera", pickupLocation: "Nyarugenge", destination: "Kicukiro", dateTime: "June 11, 2026, 10:10 PM", neededTime: "In 30 minutes", carType: "Luxury car", notes: "Call on arrival.", status: "Driver on the way", lastUpdated: "June 11, 2026, 10:14 PM" },
    { bookingId: "UM-2159", bookingType: "Quick Book", clientId: "cli-003", clientName: "Patrick Ndayisenga", driverId: "drv-004", driverName: "Eric Paul", pickupLocation: "Gasabo", destination: "Remera", dateTime: "June 10, 2026, 8:00 PM", neededTime: "ASAP", carType: "SUV", notes: "Urgent pickup.", status: "Trip started", lastUpdated: "June 10, 2026, 8:18 PM" },
    { bookingId: "UM-2178", bookingType: "Plan Ahead", clientId: "cli-004", clientName: "Nadia Umutesi", driverId: "drv-003", driverName: "Chantal Niyonsaba", pickupLocation: "Kigali International Airport", destination: "Remera", dateTime: "May 28, 2026, 11:15 PM", neededTime: "Scheduled", carType: "Automatic", notes: "Airport pickup.", status: "Completed", lastUpdated: "May 29, 2026" },
    { bookingId: "UM-2148", bookingType: "Plan Ahead", clientId: "cli-005", clientName: "Daniel Bizimana", driverId: "drv-002", driverName: "Jean Kamanzi", pickupLocation: "Musanze", destination: "Rubavu", dateTime: "June 8, 2026, 6:00 PM", neededTime: "Scheduled", carType: "Pickup", notes: "Long-distance trip.", status: "Cancelled", lastUpdated: "June 8, 2026" },
    { bookingId: "UM-2133", bookingType: "Quick Book", clientId: "cli-002", clientName: "Grace Mukamana", driverId: "drv-001", driverName: "Amina Mutesi", pickupLocation: "Kimihurura", destination: "Nyamirambo", dateTime: "June 4, 2026, 11:20 PM", neededTime: "ASAP", carType: "Automatic", notes: "Reported identity concern.", status: "Reported", lastUpdated: "June 5, 2026" },
    { bookingId: "UM-2127", bookingType: "Plan Ahead", clientId: "cli-001", clientName: "Mika Uwase", driverId: "drv-003", driverName: "Chantal Niyonsaba", pickupLocation: "Huye", destination: "Kigali", dateTime: "May 20, 2026, 3:30 PM", neededTime: "Scheduled", carType: "Manual", notes: "Intercity trip.", status: "Reviewed", lastUpdated: "May 22, 2026" },
    { bookingId: "UM-3304", bookingType: "Quick Book", clientId: "cli-001", clientName: "Mika Uwase", driverId: "drv-001", driverName: "Amina Mutesi", pickupLocation: "Kigali Convention Centre", destination: "Kiyovu", dateTime: "June 12, 2026, 8:45 PM", neededTime: "In 1 hour", carType: "Luxury car", notes: "Business dinner.", status: "Pending", lastUpdated: "June 11, 2026" },
    { bookingId: "UM-3310", bookingType: "Plan Ahead", clientId: "cli-003", clientName: "Patrick Ndayisenga", driverId: "drv-007", driverName: "Nadia Ishimwe", pickupLocation: "Kigali Arena", destination: "Gisozi", dateTime: "June 15, 2026, 10:30 PM", neededTime: "Scheduled", carType: "Automatic", notes: "Event pickup.", status: "Pending", lastUpdated: "June 11, 2026" },
    { bookingId: "UM-3320", bookingType: "Plan Ahead", clientId: "cli-005", clientName: "Daniel Bizimana", driverId: "drv-006", driverName: "Samuel Nkurunziza", pickupLocation: "Rubavu", destination: "Musanze", dateTime: "June 20, 2026, 9:00 AM", neededTime: "Scheduled", carType: "Pickup", notes: "Vehicle notes sent.", status: "Completed", lastUpdated: "June 20, 2026" }
  ],
  reviews: [
    { reviewId: "RV-1001", bookingId: "UM-2201", clientId: "cli-001", clientFirstName: "Mika", driverId: "drv-001", driverName: "Amina Mutesi", rating: 5, reviewText: "Clear communication, careful driving, and a calm trip home.", date: "June 11, 2026", flagged: false },
    { reviewId: "RV-1002", bookingId: "UM-2127", clientId: "cli-004", clientFirstName: "Nadia", driverId: "drv-002", driverName: "Jean Kamanzi", rating: 5, reviewText: "Very respectful and careful with my SUV.", date: "May 28, 2026", flagged: false },
    { reviewId: "RV-1003", bookingId: "UM-2178", clientId: "cli-003", clientFirstName: "Patrick", driverId: "drv-001", driverName: "Amina Mutesi", rating: 4, reviewText: "Pickup instructions were unclear, but the drive was smooth.", date: "June 5, 2026", flagged: false },
    { reviewId: "RV-1004", bookingId: "UM-2139", clientId: "cli-002", clientFirstName: "Grace", driverId: "drv-004", driverName: "Eric Paul", rating: 2, reviewText: "Driver arrived late and communication was unclear.", date: "June 9, 2026", flagged: true },
    { reviewId: "RV-1005", bookingId: "UM-2164", clientId: "cli-002", clientFirstName: "Grace", driverId: "drv-005", driverName: "Claudine Uwera", rating: 5, reviewText: "Professional, calm, and early to the pickup point.", date: "June 2, 2026", flagged: false },
    { reviewId: "RV-1006", bookingId: "UM-2148", clientId: "cli-005", clientFirstName: "Daniel", driverId: "drv-002", driverName: "Jean Kamanzi", rating: 4, reviewText: "Good manual driving on the highway.", date: "May 30, 2026", flagged: false },
    { reviewId: "RV-1007", bookingId: "UM-3320", clientId: "cli-005", clientFirstName: "Daniel", driverId: "drv-006", driverName: "Samuel Nkurunziza", rating: 4, reviewText: "Reliable pickup handling and smooth trip.", date: "June 20, 2026", flagged: false },
    { reviewId: "RV-1008", bookingId: "UM-2159", clientId: "cli-003", clientFirstName: "Patrick", driverId: "drv-004", driverName: "Eric Paul", rating: 1, reviewText: "Unsafe communication and wrong route concerns.", date: "June 10, 2026", flagged: true }
  ],
  incidentReports: [
    { reportId: "IR-4007", bookingId: "UM-1042", reportedBy: "Client", clientId: "cli-002", clientName: "Claude", driverId: "drv-002", driverName: "Jean Kamanzi", reportType: "Safety concern", urgency: "High", description: "Client reported unclear communication before departure.", dateSubmitted: "June 9, 2026", status: "Under Review", lastUpdated: "June 10, 2026" },
    { reportId: "IR-4004", bookingId: "UM-1038", reportedBy: "Client", clientId: "cli-003", clientName: "Sarah", driverId: "drv-004", driverName: "Eric Paul", reportType: "Driver misconduct", urgency: "Emergency", description: "Serious conduct report requiring urgent review.", dateSubmitted: "June 4, 2026", status: "New", lastUpdated: "June 4, 2026" },
    { reportId: "IR-3999", bookingId: "UM-1029", reportedBy: "Driver", clientId: "cli-005", clientName: "Daniel", driverId: "drv-001", driverName: "Amina Mutesi", reportType: "Vehicle issue", urgency: "Medium", description: "Vehicle warning light appeared during trip.", dateSubmitted: "May 30, 2026", status: "Resolved", lastUpdated: "June 2, 2026" },
    { reportId: "IR-3051", bookingId: "UM-3304", reportedBy: "Driver", clientId: "cli-001", clientName: "Mika Uwase", driverId: "drv-001", driverName: "Amina Mutesi", reportType: "Vehicle issue", urgency: "Medium", description: "Driver reported unusual brake sound.", dateSubmitted: "June 10, 2026", status: "Awaiting Response", lastUpdated: "June 11, 2026" },
    { reportId: "IR-2042", bookingId: "UM-2133", reportedBy: "Client", clientId: "cli-002", clientName: "Grace Mukamana", driverId: "drv-001", driverName: "Amina Mutesi", reportType: "Wrong driver arrived", urgency: "High", description: "Client wanted identity reviewed before trip.", dateSubmitted: "June 4, 2026", status: "Under Review", lastUpdated: "June 5, 2026" },
    { reportId: "IR-2029", bookingId: "UM-2159", reportedBy: "Client", clientId: "cli-003", clientName: "Patrick Ndayisenga", driverId: "drv-004", driverName: "Eric Paul", reportType: "Safety concern", urgency: "Low", description: "Resolved route concern after staff follow-up.", dateSubmitted: "May 30, 2026", status: "Resolved", lastUpdated: "June 2, 2026" }
  ],
  subscriptions: [
    { subscriptionId: "sub-001", driverId: "drv-001", driverName: "Amina Mutesi", plan: "Pro", monthlyFee: "5,000 RWF", paymentStatus: "Active", renewalDate: "July 8, 2026", profileVisibility: "Visible" },
    { subscriptionId: "sub-002", driverId: "drv-002", driverName: "Jean Kamanzi", plan: "Pro", monthlyFee: "5,000 RWF", paymentStatus: "Active", renewalDate: "July 12, 2026", profileVisibility: "Visible" },
    { subscriptionId: "sub-003", driverId: "drv-003", driverName: "Chantal Niyonsaba", plan: "Basic", monthlyFee: "2,500 RWF", paymentStatus: "Pending", renewalDate: "June 14, 2026", profileVisibility: "Hidden" },
    { subscriptionId: "sub-004", driverId: "drv-004", driverName: "Eric Paul", plan: "Basic", monthlyFee: "2,500 RWF", paymentStatus: "Expired", renewalDate: "June 1, 2026", profileVisibility: "Hidden" },
    { subscriptionId: "sub-005", driverId: "drv-005", driverName: "Claudine Uwera", plan: "Pro", monthlyFee: "5,000 RWF", paymentStatus: "Active", renewalDate: "July 18, 2026", profileVisibility: "Visible" },
    { subscriptionId: "sub-006", driverId: "drv-006", driverName: "Samuel Nkurunziza", plan: "Basic", monthlyFee: "2,500 RWF", paymentStatus: "Active", renewalDate: "July 3, 2026", profileVisibility: "Visible" },
    { subscriptionId: "sub-007", driverId: "drv-007", driverName: "Nadia Ishimwe", plan: "Pro", monthlyFee: "5,000 RWF", paymentStatus: "Active", renewalDate: "July 20, 2026", profileVisibility: "Visible" },
    { subscriptionId: "sub-008", driverId: "drv-008", driverName: "Patrick Habimana", plan: "Basic", monthlyFee: "2,500 RWF", paymentStatus: "Expired", renewalDate: "May 28, 2026", profileVisibility: "Hidden" }
  ],
  supportTickets: [
    { ticketId: "SUP-101", userType: "Client", fullName: "Mika Uwase", phone: "+250 788 555 010", email: "mika.uwase@example.com", issueCategory: "Booking help", bookingId: "UM-2201", message: "Need help confirming driver arrival.", status: "New", dateSubmitted: "June 11, 2026" },
    { ticketId: "SUP-102", userType: "Driver", fullName: "Amina Mutesi", phone: "+250 788 000 111", email: "amina.mutesi@example.com", issueCategory: "Subscription issue", bookingId: "", message: "Question about Pro renewal.", status: "Under Review", dateSubmitted: "June 10, 2026" },
    { ticketId: "SUP-103", userType: "Client", fullName: "Grace Mukamana", phone: "+250 788 555 020", email: "grace.m@example.com", issueCategory: "Driver issue", bookingId: "UM-2133", message: "Profile identity confirmation needed.", status: "Under Review", dateSubmitted: "June 5, 2026" },
    { ticketId: "SUP-104", userType: "Admin", fullName: "Ops Staff", phone: "+250 788 000 222", email: "support@umusare.rw", issueCategory: "Technical problem", bookingId: "", message: "Demo admin ticket for support workflow.", status: "Resolved", dateSubmitted: "June 2, 2026" },
    { ticketId: "SUP-105", userType: "Other", fullName: "Visitor", phone: "+250 788 555 090", email: "visitor@example.com", issueCategory: "Other", bookingId: "", message: "General platform question.", status: "New", dateSubmitted: "June 1, 2026" }
  ]
};
